// Generated from contract.ts by scripts/telemetry-shape.js: do not edit.
// The structured fields of every event; everything else goes under `extra`.

/** true = keep whole; an object = only these keys stay, each with its own shape; '[]' = each array element. */
export type Shape = true | { [key: string]: Shape };

/** The structured fields of the envelope's `client`. */
export const CLIENT_FIELDS: readonly string[] = [
  'environment',
  'sdk',
  'sdk_version',
  'os',
  'os_version',
  'user_agent',
];

export const STRUCTURED_SHAPE: Readonly<Record<string, Shape>> = {
  sdk_creation_started: {
    options: {
      login: true,
      debug: true,
      login_type: true,
      explicit_rtc_provided: true,
      use_canary: true,
      skip_trailing: true,
      region: true,
      keep_connection_alive_on_socket_close: true,
      hangup_on_before_unload: true,
      trickle_ice: true,
      prefetch_ice_candidates: true,
      force_relay_candidate: true,
      muted_mic_on_start: true,
      push_when_active: true,
      early_sdp_answer: true,
      media_permissions_recovery: true,
      ice_servers: {
        '[]': {
          url: true,
          has_credential: true,
        },
      },
      custom_ice_servers: true,
      push_provider: true,
      log_level: true,
      telemetry: {
        enabled: true,
        metrics_interval_ms: true,
        max_pending_events: true,
        max_send_backlog_bytes: true,
      },
    },
    raw_client_options: true,
  },
  sdk_creation_failed: {
    error: {
      name: true,
      message: true,
      code: true,
      server_code: true,
      server_message: true,
      stack: true,
    },
  },
  sdk_created: {
    creation_duration_ms: true,
    sdk_instances: true,
  },
  network_changed: {
    initial: true,
    network_type: true,
    online: true,
    effective_type: true,
    downlink_mbps: true,
  },
  app_state_changed: {
    state: true,
  },
  input_device_changed: {
    by: true,
    device_count: true,
  },
  output_device_changed: {
    by: true,
    device_count: true,
  },
  device_list_changed: {
    input_count: true,
    output_count: true,
    added: true,
    removed: true,
  },
  socket_connect_started: {
    target: {
      url: true,
      region: true,
      rtc_ip: true,
      rtc_port: true,
      use_canary_server: true,
      skip_last_voice_sdk_id: true,
      skip_trailing: true,
      resume_voice_sdk_id: true,
    },
    is_reconnect: true,
  },
  socket_failed: {
    error: {
      name: true,
      message: true,
      code: true,
      server_code: true,
      server_message: true,
      stack: true,
    },
    close_code: true,
    attempt: true,
    will_retry: true,
  },
  socket_connected: {
    connect_duration_ms: true,
    region: true,
    dc: true,
    node: true,
  },
  socket_closed: {
    close_code: true,
    reason: true,
    closed_by: true,
    open_duration_ms: true,
    will_reconnect: true,
    in_background: true,
  },
  login_started: {
    method: {
      login_type: true,
      username: true,
      target_type: true,
      target_id: true,
    },
    is_reconnect: true,
    resume_session_id: true,
  },
  login_failed: {
    signaling_region: true,
    signaling_dc: true,
    signaling_node: true,
    method: {
      login_type: true,
      username: true,
      target_type: true,
      target_id: true,
    },
    is_reconnect: true,
    error: {
      name: true,
      message: true,
      code: true,
      server_code: true,
      server_message: true,
      stack: true,
    },
    will_retry: true,
  },
  login_succeeded: {
    signaling_region: true,
    signaling_dc: true,
    signaling_node: true,
    method: {
      login_type: true,
      username: true,
      target_type: true,
      target_id: true,
    },
    is_reconnect: true,
    login_duration_ms: true,
  },
  client_ready: {
    signaling_region: true,
    signaling_dc: true,
    signaling_node: true,
    is_reconnect: true,
    time_to_ready_ms: true,
    connect_to_ready_ms: true,
    app_wait_ms: true,
    socket_connect_ms: true,
    login_ms: true,
    login_to_ready_ms: true,
    socket_attempts: true,
    login_attempts: true,
    started_by_push: true,
    push_to_ready_ms: true,
    remote_element_provided: true,
    mic_id_provided: true,
    speaker_id_provided: true,
    reattached_call_ids: true,
  },
  gateway_state: {
    state: true,
    raw_state: true,
    previous_state: true,
  },
  gateway_check_started: {
    check_number: true,
  },
  gateway_check_succeeded: {
    check_number: true,
    state: true,
    raw_state: true,
    response_time_ms: true,
  },
  gateway_check_failed: {
    check_number: true,
    error: {
      name: true,
      message: true,
      code: true,
      server_code: true,
      server_message: true,
      stack: true,
    },
    will_retry: true,
  },
  signaling_message: {
    direction: true,
    raw: true,
  },
  call_started: {
    b2bua_rtc_node: true,
    b2bua_rtc_region: true,
    b2bua_rtc_dc: true,
    direction: true,
    caller_number: true,
    caller_name: true,
    destination_number: true,
    audio: true,
    video: true,
    trickle_ice: true,
    force_relay_candidate: true,
    prefetch_ice_candidates: true,
    keep_connection_alive_on_socket_close: true,
    custom_ice_servers: true,
    ice_servers_count: true,
    use_stereo: true,
    use_sdp_as_bandwidth: true,
    sdp_as_bandwidth_kbps: true,
    preferred_codecs: true,
    custom_header_names: true,
    remote_element_provided: true,
    local_element_provided: true,
    mic_id_provided: true,
    speaker_id_provided: true,
    camera_id_provided: true,
    is_reattach: true,
    signaling_region: true,
    signaling_dc: true,
    signaling_node: true,
  },
  call_state: {
    b2bua_rtc_node: true,
    b2bua_rtc_region: true,
    b2bua_rtc_dc: true,
    state: true,
    previous_state: true,
  },
  ice_candidate: {
    candidate_type: true,
    protocol: true,
    relay_protocol: true,
    network_type: true,
    foundation: true,
    priority: true,
    tcp_type: true,
    related_address: true,
    related_port: true,
    address: true,
    port: true,
    url: true,
    side: true,
    ice_generation: true,
    component: true,
    since_gathering_started_ms: true,
    signaled: true,
  },
  call_media_changed: {
    changed: true,
    codec_in: {
      mime_type: true,
      clock_rate: true,
      channels: true,
      payload_type: true,
      sdp_fmtp_line: true,
    },
    codec_out: {
      mime_type: true,
      clock_rate: true,
      channels: true,
      payload_type: true,
      sdp_fmtp_line: true,
    },
    target_bitrate_bps: true,
    local_candidate: {
      candidate_type: true,
      protocol: true,
      relay_protocol: true,
      network_type: true,
      foundation: true,
      priority: true,
      tcp_type: true,
      related_address: true,
      related_port: true,
      address: true,
      port: true,
      url: true,
    },
    remote_candidate: {
      candidate_type: true,
      protocol: true,
      relay_protocol: true,
      network_type: true,
      foundation: true,
      priority: true,
      tcp_type: true,
      related_address: true,
      related_port: true,
      address: true,
      port: true,
      url: true,
    },
    previous_local_candidate: {
      candidate_type: true,
      protocol: true,
      relay_protocol: true,
      network_type: true,
      foundation: true,
      priority: true,
      tcp_type: true,
      related_address: true,
      related_port: true,
      address: true,
      port: true,
      url: true,
    },
    previous_remote_candidate: {
      candidate_type: true,
      protocol: true,
      relay_protocol: true,
      network_type: true,
      foundation: true,
      priority: true,
      tcp_type: true,
      related_address: true,
      related_port: true,
      address: true,
      port: true,
      url: true,
    },
    pair_changes: true,
    ice_state: true,
    dtls_state: true,
    srtp_cipher: true,
    dtls_version: true,
    sending: true,
    input_device: {
      label: true,
      enabled: true,
      muted: true,
      ready_state: true,
      auto_gain_control: true,
      echo_cancellation: true,
      noise_suppression: true,
      sample_rate: true,
      sample_size: true,
      channel_count: true,
      latency_ms: true,
    },
    output_device_label: true,
    input_device_count: true,
    output_device_count: true,
    echo_return_loss_db: true,
    echo_return_loss_enhancement_db: true,
  },
  call_metrics: {
    interval_ms: true,
    rtt_ms: true,
    rtcp_rtt_ms: true,
    jitter_ms: true,
    remote_jitter_ms: true,
    in_packets: true,
    in_bytes: true,
    in_lost: true,
    in_discarded: true,
    in_fec_packets: true,
    in_samples: true,
    in_concealed_samples: true,
    in_concealment_events: true,
    played_samples: true,
    synthesized_ms: true,
    jitter_buffer_ms: true,
    jitter_buffer_target_ms: true,
    playout_delay_ms: true,
    in_level: true,
    out_packets: true,
    out_bytes: true,
    out_retransmitted_packets: true,
    out_nacks: true,
    out_send_delay_ms: true,
    out_level: true,
    remote_lost: true,
    remote_sent_packets: true,
    ice_requests: true,
    ice_responses: true,
    counters_reset: true,
  },
  call_warning: {
    code: true,
    name: true,
    metric: true,
    value: true,
    threshold: true,
  },
  call_timings: {
    complete: true,
    answer_called_ms: true,
    peer_created_ms: true,
    media_devices_acquired_ms: true,
    peer_setup_complete_ms: true,
    sdp_negotiation_started_ms: true,
    sdp_local_created_ms: true,
    local_description_applied_ms: true,
    ice_gathering_started_ms: true,
    sdp_sent_ms: true,
    first_ice_candidate_ms: true,
    first_srflx_or_relay_candidate_ms: true,
    all_ice_candidates_gathered_ms: true,
    remote_ringing_ms: true,
    early_media_ms: true,
    remote_answered_ms: true,
    first_remote_track_ms: true,
    remote_description_applied_ms: true,
    call_active_ms: true,
    ice_connected_ms: true,
    dtls_connected_ms: true,
    first_packet_received_ms: true,
  },
  call_ended: {
    end_reason: true,
    cause: true,
    cause_code: true,
    sip_code: true,
    sip_reason: true,
    last_state: true,
    answered: true,
    duration_ms: true,
    talk_ms: true,
    metrics_samples: true,
    totals: {
      in_packets: true,
      in_bytes: true,
      in_lost: true,
      in_discarded: true,
      in_samples: true,
      in_concealed_samples: true,
      in_concealment_events: true,
      out_packets: true,
      out_bytes: true,
      out_retransmitted_packets: true,
      out_nacks: true,
      remote_lost: true,
      rtt_avg_ms: true,
      rtt_max_ms: true,
      rtcp_rtt_avg_ms: true,
      pair_changes: true,
    },
  },
  network_route_measured: {
    tool: true,
    trigger: true,
    target: true,
    protocol: true,
    port: true,
    packet_size_bytes: true,
    probes_per_hop: true,
    duration_ms: true,
    hops: {
      '[]': {
        hop: true,
        host: true,
        loss_pct: true,
        sent: true,
        last_ms: true,
        avg_ms: true,
        best_ms: true,
        worst_ms: true,
        stdev_ms: true,
      },
    },
  },
  logs: {
    level: true,
    category: true,
    message: true,
    details: true,
  },
  error: {
    stage: true,
    error: {
      name: true,
      message: true,
      code: true,
      server_code: true,
      server_message: true,
      stack: true,
    },
    is_fatal: true,
    details: true,
  },
};
