name: publish-gh-pages

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate and validate Markdown and HTML public API docs
        working-directory: packages/js
        run: yarn docs:check

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/js/docs/ts
          clean: true
